import {renderManager} from './manager.js';
import {BookingStore,scheduledSlots,today,available,statuses,formatDate} from './booking.js';
const app=document.querySelector('#app'), store=new BookingStore();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let draft={people:2,date:today(),time:'',first:'',last:'',phone:'',notes:''}, step=1, adminDate=today(), filter='all';
const $=s=>document.querySelector(s);
const notify=text=>{const t=$('#toast');t.textContent=text;t.style.display='block';setTimeout(()=>t.style.display='none',3500)};
const options=(items,val)=>items.map(x=>`<option value="${esc(x)}" ${String(x)===String(val)?'selected':''}>${esc(x)}</option>`).join('');
const peopleOptions=v=>Array.from({length:30},(_,i)=>`<option value="${i+1}" ${i+1===Number(v)?'selected':''}>${i+1} ${i?'persone':'persona'}</option>`).join('');
function summary(b){return `<div class="summary"><strong>${esc(formatDate(b.date))}</strong><p>${esc(b.time)} · ${Number(b.people)} ${Number(b.people)===1?'persona':'persone'}</p>${b.first?`<p>${esc(b.first)} ${esc(b.last)}</p><p>${esc(b.phone)}</p>`:''}${b.notes?`<p>Note: ${esc(b.notes)}</p>`:''}</div>`}
function route(path){history.pushState({},'',path);render();window.scrollTo(0,0)}
function render(){if(location.pathname.startsWith('/admin'))admin();else if(location.pathname==='/conferma')receipt();else booking()}
function booking(){app.innerHTML=`<div class="booking-layout"><section class="intro"><span class="eyebrow">Bem-vindo ao Recanto</span><h1>Il tuo tavolo.<br>Il nostro <em>Brasile.</em></h1><p>Ritroviamoci a tavola. Scegli quando venire e prenota il tuo momento al Recanto Brasil.</p><div class="restaurant-card"><span class="seal">R</span><div><strong>Recanto Brasil</strong><small>Churrascaria · Il piacere di stare insieme</small></div></div></section><section class="panel" aria-labelledby="form-title"><div class="steps"><span class="${step===1?'active':''}"><i>1</i>Il tuo tavolo</span><span class="${step===2?'active':''}"><i>2</i>I tuoi dati</span></div><div class="notice-box">Modalità demo: nessuna prenotazione reale. Usa dati fittizi. Le prove sono salvate solo in questo browser.</div>${step===1?`<h2 id="form-title">Prenota un tavolo</h2><p class="sub">Bastano pochi istanti.</p><form id="table-form"><div class="row"><label class="field"><span>Persone</span><select id="people" name="people">${peopleOptions(draft.people)}</select></label><label class="field"><span>Data</span><input type="date" id="date" name="date" required min="${today()}" value="${draft.date}"></label></div><span class="label">Scegli l’orario</span><p class="sub">Orari e disponibilità dimostrativi.</p><div class="slots" id="slots"></div><p id="slot-error" class="error" role="alert"></p><button class="wide" type="submit">Continua →</button></form>`:`<button class="text-button" id="back">← Cambia data e orario</button><h2 id="form-title">Ci conosciamo?</h2><p class="sub">Inserisci i dati per completare la prova.</p>${summary(draft)}<form id="guest-form">${guestFields(draft)}<label class="checkline"><input type="checkbox" required> <span>Ho capito che è una demo e sto utilizzando dati fittizi.</span></label><p id="guest-error" class="error" role="alert"></p><button class="wide" type="submit">Conferma prenotazione demo</button></form>`}<p class="notice">Nessun pagamento richiesto · Nessun messaggio inviato</p></section></div>`;
if(step===1){drawSlots();$('#people').onchange=e=>{draft.people=Number(e.target.value);draft.time='';drawSlots()};$('#date').onchange=e=>{draft.date=e.target.value;draft.time='';drawSlots()};$('#table-form').onsubmit=e=>{e.preventDefault();if(!draft.time){$('#slot-error').textContent='Scegli un orario disponibile.';return}step=2;booking();$('#first').focus()}}else{$('#back').onclick=()=>{Object.assign(draft,readGuest());step=1;booking()};$('#guest-form').onsubmit=e=>{e.preventDefault();Object.assign(draft,readGuest());try{const b=store.create({...draft,source:'online',status:'prenotato'});sessionStorage.setItem('recanto-last-booking',JSON.stringify(b));route('/conferma')}catch(err){$('#guest-error').textContent=err.message}}}}
function drawSlots(){const list=available(store.list(),draft.date,draft.people,store.settings());$('#slots').innerHTML=scheduledSlots(draft.date,store.settings()).map(t=>`<button type="button" class="slot ${draft.time===t?'selected':''}" aria-pressed="${draft.time===t}" data-time="${t}" ${list.includes(t)?'':'disabled'}>${t}</button>`).join('');$('#slots').querySelectorAll('button').forEach(b=>b.onclick=()=>{draft.time=b.dataset.time;drawSlots();$('#slot-error').textContent=''});if(!list.length)$('#slot-error').textContent='Nessun orario disponibile per questa data. Scegli un altro giorno.';else $('#slot-error').textContent=''}
function guestFields(b){return `<div class="row"><label class="field"><span>Nome</span><input id="first" name="first" required maxlength="60" autocomplete="given-name" value="${esc(b.first)}"></label><label class="field"><span>Cognome</span><input id="last" name="last" required maxlength="60" autocomplete="family-name" value="${esc(b.last)}"></label></div><label class="field"><span>Telefono</span><input id="phone" name="phone" type="tel" inputmode="tel" required maxlength="25" placeholder="Es. 000 1234567 (demo)" value="${esc(b.phone)}"></label><label class="field"><span>Note <span class="sub">· facoltative</span></span><textarea id="notes" name="notes" maxlength="500" placeholder="Es. un seggiolone per un bambino">${esc(b.notes)}</textarea></label>`}
function readGuest(){return Object.fromEntries(['first','last','phone','notes'].map(k=>[k,$('#'+k).value.trim()]))}
function receipt(){let b;try{b=JSON.parse(sessionStorage.getItem('recanto-last-booking'))}catch{}if(!b){app.innerHTML='<section class="panel success"><h1>Nessun riepilogo disponibile</h1><p>Completa una prenotazione per visualizzarla qui.</p><a class="button" href="/">Prenota un tavolo</a></section>';return}app.innerHTML=`<section class="panel success"><div class="success-mark">✓</div><span class="eyebrow">Ti aspettiamo a tavola</span><h1>Prenotazione demo registrata</h1><p class="sub">Il riepilogo della tua prova al Recanto Brasil.</p><div class="code">${esc(b.id)}</div>${summary(b)}<p class="notice-box">È una simulazione: il ristorante non ha ricevuto la prenotazione. Nessun SMS, WhatsApp o email è stato inviato.</p><button id="another" class="wide">Fai un’altra prova</button><a class="text-button" href="/admin">Visualizza nell’area amministratore →</a></section>`;$('#another').onclick=()=>{draft={people:2,date:today(),time:'',first:'',last:'',phone:'',notes:''};step=1;route('/')}}
function admin(){renderManager(app,store)}
window.addEventListener('popstate',render);window.addEventListener('storage',e=>{if([store.key,store.metaKey,store.logKey].includes(e.key))render()});render();
