// Replace this repository adapter with authenticated server APIs for shared bookings.
// Integrations intentionally disabled: no external requests or credentials.
export const integrations=Object.freeze({whatsapp:{enabled:false},googleBusinessProfile:{enabled:false},facebook:{enabled:false},instagram:{enabled:false}});
export const slots=['12:00','12:30','13:00','13:30','19:00','19:30','20:00','20:30','21:00','21:30'];
export const statuses=['prenotato','confermato','arrivato','no-show','cancellato'];
const CAPACITY=40,DURATION=120;
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
export function formatDate(d){return new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'))}
const minutes=t=>Number(t.slice(0,2))*60+Number(t.slice(3));
const active=b=>!['cancellato','no-show'].includes(b.status);
function future(date,time){if(date>today())return true;if(date<today())return false;const now=new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date());return time>now}
function fits(rows,date,time,people,except){const start=minutes(time),end=start+DURATION;const overlaps=rows.filter(b=>b.id!==except&&b.date===date&&active(b)&&minutes(b.time)<end&&minutes(b.time)+DURATION>start);return [start,...overlaps.map(b=>minutes(b.time)).filter(t=>t>=start)].every(t=>Number(people)+overlaps.filter(b=>minutes(b.time)<=t&&minutes(b.time)+DURATION>t).reduce((n,b)=>n+b.people,0)<=CAPACITY)}
export function available(rows,date,people){return slots.filter(t=>future(date,t)&&fits(rows,date,t,people))}
function validate(b){if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||Number.isNaN(Date.parse(b.date+'T12:00:00'))||new Date(b.date+'T12:00:00Z').toISOString().slice(0,10)!==b.date)throw Error('Scegli una data valida.');if(!Number.isInteger(b.people)||b.people<1||b.people>30)throw Error('Scegli da 1 a 30 persone.');if(!slots.includes(b.time))throw Error('Scegli un orario valido.');if(!b.first?.trim()||!b.last?.trim()||b.first.length>60||b.last.length>60)throw Error('Inserisci nome e cognome validi.');if(!/^[+\d\s().-]{7,25}$/.test(b.phone)||b.phone.replace(/\D/g,'').length<7)throw Error('Inserisci un telefono di prova valido, con almeno 7 cifre.');if((b.notes||'').length>500)throw Error('Le note possono contenere al massimo 500 caratteri.');if(!statuses.includes(b.status))throw Error('Stato non valido.')}
export class BookingStore{
constructor(storage=localStorage){this.storage=storage;this.key='recanto-booking-demo-v1';if(storage.getItem(this.key)===null){const names=[['Marco','Demo',4,'19:00','confermato'],['Sofia','Esempio',2,'19:30','prenotato'],['Luca','Prova',6,'20:00','confermato'],['Ana','Demo',3,'12:30','arrivato'],['Paolo','Esempio',2,'13:00','no-show'],['Giulia','Prova',5,'21:00','cancellato']];this.save(names.map((n,i)=>({id:'RB-DEMO'+(i+1),first:n[0],last:n[1],people:n[2],time:n[3],status:n[4],date:today(),phone:'000 000 000'+i,notes:i===2?'Un seggiolone · esempio':'',source:'demo'})))}}
list(){try{const rows=JSON.parse(this.storage.getItem(this.key)||'[]');if(!Array.isArray(rows))throw Error();return rows}catch{throw Error('I dati demo non sono leggibili. Ripristina i dati del sito nel browser.')}}
save(rows){try{this.storage.setItem(this.key,JSON.stringify(rows))}catch{throw Error('Salvataggio non riuscito. Consenti la memorizzazione dei dati nel browser.')}}
create(data){const rows=this.list(),b={...data,id:'RB-'+crypto.randomUUID().slice(0,8).toUpperCase(),createdAt:new Date().toISOString()};validate(b);if(!future(b.date,b.time))throw Error('Seleziona un orario futuro.');if(active(b)&&!fits(rows,b.date,b.time,b.people))throw Error('Non ci sono abbastanza posti per questo orario. Scegline un altro.');this.save([...rows,b]);return b}
update(id,data){const rows=this.list(),old=rows.find(b=>b.id===id);if(!old)throw Error('Prenotazione non trovata.');const b={...old,...data,id,updatedAt:new Date().toISOString()};validate(b);if((b.date!==old.date||b.time!==old.time)&&!future(b.date,b.time))throw Error('Seleziona un orario futuro.');if(active(b)&&!fits(rows,b.date,b.time,b.people,id))throw Error('Non ci sono abbastanza posti per questo orario.');this.save(rows.map(x=>x.id===id?b:x));return b}
}
