// Demo repository. Production needs authenticated APIs and transactional storage.
export const integrations=Object.freeze({whatsapp:{enabled:false},googleBusinessProfile:{enabled:false},facebook:{enabled:false},instagram:{enabled:false}});
export const slots=[...Array.from({length:9},(_,i)=>clock(720+i*15)),...Array.from({length:13},(_,i)=>clock(1140+i*15))];
export const statuses=['prenotato','confermato','riconfermato','arrivo parziale','arrivato','uscito','no-show','cancellato'];
export const tables=Array.from({length:25},(_,i)=>({id:'T'+(i+1),seats:i<20?4:10,room:i<15?'Sala principale':'Seconda sala'}));
export const weekdays=['Domenica','Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato'];
export const manualSlots=Array.from({length:96},(_,i)=>clock(i*15));
export function defaultWeek(){return Array.from({length:7},()=>({open:true,pranzo:{enabled:true,start:'12:00',end:'14:00'},cena:{enabled:true,start:'19:00',end:'22:00'}}))}
export const defaults={capacity:130,duration:120,closed:{},weekly:defaultWeek()};
export function dayHours(date,config=defaults){return (config.weekly||defaults.weekly)[new Date(date+'T12:00:00Z').getUTCDay()]}
export function scheduledSlots(date,config=defaults){const day=dayHours(date,config);if(!day?.open)return [];return ['pranzo','cena'].flatMap(svc=>{const h=day[svc];if(!h.enabled)return [];return Array.from({length:Math.floor((minutes(h.end)-minutes(h.start))/15)+1},(_,i)=>clock(minutes(h.start)+i*15))})}
export function onlineOpen(date,svc,config=defaults){const d=dayHours(date,config);return !!(d?.open&&d[svc]?.enabled&&!config.closed?.[date+'|'+svc])}
function validateWeek(week){if(!Array.isArray(week)||week.length!==7)throw Error('Imposta tutti i giorni della settimana.');week.forEach((day,i)=>{if(typeof day.open!=='boolean')throw Error('Giorno non valido.');for(const svc of ['pranzo','cena']){const h=day[svc];if(!h||typeof h.enabled!=='boolean'||![h.start,h.end].every(t=>manualSlots.includes(t))||h.start>h.end||service(h.start)!==svc||service(h.end)!==svc)throw Error(weekdays[i]+': controlla gli orari di '+svc+'. Pranzo prima delle 17:00, cena dalle 17:00, intervalli di 15 minuti.');}if(day.open&&!day.pranzo.enabled&&!day.cena.enabled)throw Error(weekdays[i]+': attiva almeno un servizio oppure segna il giorno come chiuso.');})}

export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
export function nowTime(){return new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date())}
export function formatDate(d){return new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'))}
export function minutes(t){return Number(t.slice(0,2))*60+Number(t.slice(3))}
export function clock(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
export const service=t=>t<'17:00'?'pranzo':'cena';
export const active=b=>!['cancellato','no-show','uscito'].includes(b.status);
export const expected=b=>!['cancellato','no-show'].includes(b.status);
export function future(date,time){return date>today()||(date===today()&&time>nowTime())}
const end=b=>minutes(b.time)+(b.duration||120);
export function overlap(a,b){return a.date===b.date&&minutes(a.time)<end(b)&&end(a)>minutes(b.time)}
export function fits(rows,b,capacity=130){const others=rows.filter(x=>x.id!==b.id&&active(x)&&overlap(x,b));return [minutes(b.time),...others.map(x=>minutes(x.time)).filter(t=>t>=minutes(b.time))].every(t=>b.people+others.filter(x=>minutes(x.time)<=t&&end(x)>t).reduce((n,x)=>n+x.people,0)<=capacity)}
export function available(rows,date,people,config=defaults){return scheduledSlots(date,config).filter(time=>future(date,time)&&!config.closed?.[date+'|'+service(time)]&&fits(rows,{date,time,people:Number(people),duration:config.duration},config.capacity))}
export function tableBusy(rows,tableId,b){return rows.some(x=>x.id!==b.id&&active(x)&&(x.tables||[]).includes(tableId)&&overlap(x,b))}
function validate(b,currentTables=tables){if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||Number.isNaN(Date.parse(b.date+'T12:00:00'))||new Date(b.date+'T12:00:00Z').toISOString().slice(0,10)!==b.date)throw Error('Scegli una data valida.');if(!Number.isInteger(b.people)||b.people<1||b.people>30)throw Error('Scegli da 1 a 30 persone.');if(!manualSlots.includes(b.time))throw Error('Scegli un orario valido.');if(!b.first?.trim()||!b.last?.trim()||b.first.length>60||b.last.length>60)throw Error('Inserisci nome e cognome validi.');if(!/^[+\d\s().-]{7,25}$/.test(b.phone)||b.phone.replace(/\D/g,'').length<7)throw Error('Inserisci un telefono valido con almeno 7 cifre.');if((b.notes||'').length>500||(b.internalNotes||'').length>1000)throw Error('Note troppo lunghe.');if(!statuses.includes(b.status))throw Error('Stato non valido.');if(!Number.isInteger(b.duration)||b.duration<30||b.duration>360)throw Error('Durata da 30 a 360 minuti.');if(!Number.isInteger(b.arrivedCount)||b.arrivedCount<0||b.arrivedCount>b.people)throw Error('Controlla il numero di persone arrivate.');if(b.status==='arrivo parziale'&&(b.arrivedCount===0||b.arrivedCount>=b.people))throw Error('Per un arrivo parziale indica da 1 a '+(b.people-1)+' persone.');if((active(b)&&(b.tables||[]).some(t=>!currentTables.some(x=>x.id===t)))||new Set(b.tables).size!==b.tables.length)throw Error('Selezione tavoli non valida.')}
export class BookingStore{
constructor(storage=localStorage){this.storage=storage;this.key='recanto-booking-demo-v1';this.metaKey='recanto-booking-settings-v2';this.logKey='recanto-booking-events-v2';if(storage.getItem(this.key)===null)this.seed()}
read(key,fallback){try{return JSON.parse(this.storage.getItem(key)||JSON.stringify(fallback))}catch{throw Error('I dati demo non sono leggibili.')}}
write(key,data){try{this.storage.setItem(key,JSON.stringify(data))}catch{throw Error('Salvataggio non riuscito. Consenti la memorizzazione dei dati nel browser.')}}
list(){const rows=this.read(this.key,[]);if(!Array.isArray(rows))throw Error('Archivio demo non valido.');return rows.map(b=>({duration:120,tables:[],internalNotes:'',occasion:'',arrivedCount:b.status==='arrivato'?b.people:0,...b}))}
save(rows){this.write(this.key,rows)}
layout(){return this.read('recanto-booking-layout-v1',{rooms:['Sala principale','Seconda sala'],tables:tables.map(t=>({...t,name:t.id}))})}
setLayout(layout){
if(!Array.isArray(layout.rooms)||!layout.rooms.length||layout.rooms.length>20||layout.rooms.some(r=>typeof r!=='string'||!r.trim()||r.length>60)||new Set(layout.rooms.map(r=>r.trim().toLocaleLowerCase())).size!==layout.rooms.length)throw Error('Inserisci da 1 a 20 sale con nomi diversi.');
if(!Array.isArray(layout.tables)||!layout.tables.length||layout.tables.length>200)throw Error('Inserisci da 1 a 200 tavoli.');
const names=new Set(),ids=new Set();for(const t of layout.tables){if(typeof t.id!=='string'||!/^[-a-zA-Z0-9]+$/.test(t.id)||ids.has(t.id)||typeof t.name!=='string'||!t.name.trim()||t.name.length>30||names.has(t.name.trim().toLocaleLowerCase())||!layout.rooms.includes(t.room)||!Number.isInteger(t.seats)||t.seats<1||t.seats>30)throw Error('Ogni tavolo deve avere un nome unico e da 1 a 30 posti.');ids.add(t.id);names.add(t.name.trim().toLocaleLowerCase());}
const capacity=layout.tables.reduce((n,t)=>n+t.seats,0);if(capacity>500)throw Error('La demo supporta al massimo 500 posti totali.');const rows=this.list();for(const b of rows.filter(b=>active(b)&&b.date>=today())){if(b.tables.some(id=>!ids.has(id)))throw Error('Un tavolo da rimuovere è assegnato a una prenotazione attiva: riassegnala prima.');if(b.tables.length&&layout.tables.filter(t=>b.tables.includes(t.id)).reduce((n,t)=>n+t.seats,0)<b.people)throw Error('I nuovi posti non bastano per una prenotazione già assegnata.');if(!fits(rows,b,capacity))throw Error('I nuovi posti totali non bastano per le prenotazioni già presenti.');}
const key='recanto-booking-layout-v1',old=this.storage.getItem(key);this.write(key,layout);try{this.setSettings({capacity})}catch(e){if(old===null)this.storage.removeItem?this.storage.removeItem(key):this.write(key,{rooms:['Sala principale','Seconda sala'],tables:tables.map(t=>({...t,name:t.id}))});else this.storage.setItem(key,old);throw e;}return layout;}
settings(){return {...defaults,...this.read(this.metaKey,{}),closed:{...this.read(this.metaKey,{}).closed},weekly:this.read(this.metaKey,{}).weekly||defaultWeek()}}
setSettings(data){const next={...this.settings(),...data};validateWeek(next.weekly);if(!Number.isInteger(next.capacity)||next.capacity<1||next.capacity>500)throw Error('Capienza da 1 a 500 coperti.');if(next.capacity>this.layout().tables.reduce((n,t)=>n+t.seats,0))throw Error('La capienza non può superare i posti configurati nei tavoli.');if(!Number.isInteger(next.duration)||next.duration<30||next.duration>360)throw Error('Durata da 30 a 360 minuti.');if(this.list().some(b=>active(b)&&b.date>=today()&&!fits(this.list(),b,next.capacity)))throw Error('La capienza scelta è inferiore alle prenotazioni già presenti.');this.write(this.metaKey,next);return next}
setClosed(date,svc,closed){if(!['pranzo','cena'].includes(svc))throw Error('Scegli un servizio.');const c=this.settings();c.closed[date+'|'+svc]=closed;this.write(this.metaKey,c)}
events(){return this.read(this.logKey,[])}
log(b,action){try{this.write(this.logKey,[{id:crypto.randomUUID(),bookingId:b.id,date:b.date,time:b.time,people:b.people,name:b.first+' '+b.last,action,at:new Date().toISOString(),read:false},...this.events()].slice(0,200))}catch{/* Booking remains saved if event storage is full. */}}
markRead(){this.write(this.logKey,this.events().map(e=>({...e,read:true})))}
check(rows,b){const currentTables=this.layout().tables;validate(b,currentTables);if(!active(b))return;if(!fits(rows,b,this.settings().capacity))throw Error('Capienza esaurita per questo intervallo.');if(b.tables.length){const seats=currentTables.filter(t=>b.tables.includes(t.id)).reduce((n,t)=>n+t.seats,0);if(seats<b.people)throw Error('I tavoli selezionati hanno solo '+seats+' posti.');if(b.tables.some(t=>tableBusy(rows,t,b)))throw Error('Uno dei tavoli è già assegnato nello stesso intervallo.')}}
create(data){const rows=this.list(),b={duration:this.settings().duration,tables:[],internalNotes:'',occasion:'',arrivedCount:0,...data,id:'RB-'+crypto.randomUUID().slice(0,8).toUpperCase(),createdAt:new Date().toISOString()};if(b.status==='arrivato')b.arrivedCount=b.people;if(b.source==='online'&&(!scheduledSlots(b.date,this.settings()).includes(b.time)||!onlineOpen(b.date,service(b.time),this.settings())))throw Error('Il giorno o l’orario scelto non è aperto alle prenotazioni online. Scegli un altro orario.');if(!future(b.date,b.time)&&!(b.source==='walkin'&&b.date===today()))throw Error('Seleziona un orario futuro.');this.check(rows,b);this.save([...rows,b]);this.log(b,'Nuova prenotazione');return b}
update(id,data){const rows=this.list(),old=rows.find(b=>b.id===id);if(!old)throw Error('Prenotazione non trovata.');const b={...old,...data,id,updatedAt:new Date().toISOString()};if(b.status==='arrivato')b.arrivedCount=b.people;else if(b.status!=='arrivo parziale')b.arrivedCount=0;if((b.date!==old.date||b.time!==old.time)&&!future(b.date,b.time))throw Error('Seleziona un orario futuro.');this.check(rows,b);this.save(rows.map(x=>x.id===id?b:x));this.log(b,b.status!==old.status?'Stato: '+b.status:'Prenotazione modificata');return b}
seed(){const names=[['Marco','Demo',8,'12:15','confermato',['T21']],['Sofia','Esempio',4,'12:30','arrivato',['T1']],['Luca','Prova',22,'12:45','riconfermato',['T22','T23','T2']],['Ana','Demo',3,'13:00','arrivo parziale',['T3']],['Paolo','Esempio',2,'13:15','no-show',[]],['Giulia','Prova',5,'19:00','cancellato',[]],['Carlo','Demo',6,'19:30','confermato',['T24']],['Elena','Esempio',4,'19:30','prenotato',[]],['Gruppo','Demo',30,'20:00','prenotato',[]],['Marta','Prova',2,'20:30','prenotato',[]]];this.save(names.map((n,i)=>({id:'RB-DEMO'+(i+1),first:n[0],last:n[1],people:n[2],time:n[3],status:n[4],tables:n[5],date:today(),duration:120,arrivedCount:n[4]==='arrivato'?n[2]:n[4]==='arrivo parziale'?1:0,phone:'000 000 000'+i,notes:i===2?'Gruppo numeroso · esempio':'',internalNotes:'',occasion:i===2?'Compleanno':'',source:'demo'})))}
loadScenario(date){if(this.list().some(b=>b.date===date))throw Error('Scegli una giornata vuota per caricare lo scenario.');const rows=Array.from({length:5},(_,i)=>({id:'RB-'+crypto.randomUUID().slice(0,8).toUpperCase(),first:'Gruppo',last:'Demo '+(i+1),people:i===4?10:30,date,time:'19:30',status:'confermato',source:'demo',phone:'0000000000',duration:120,tables:[],arrivedCount:0,notes:'Scenario di prova: sala completa, 130 persone',internalNotes:'',occasion:''}));const combined=[...this.list(),...rows];rows.forEach(b=>this.check(combined,b));this.save(combined);this.log(rows[0],'Caricato scenario da 130 coperti')}
}
