import test from 'node:test';import assert from 'node:assert/strict';import {BookingStore,available,today} from './booking.js';
function setup(){const m=new Map;const s=new BookingStore({getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)});s.save([]);return s}
const sample={first:'Test',last:'Demo',people:30,date:'2099-01-01',time:'19:00',phone:'0001234567',notes:'',status:'prenotato',source:'online'};
test('130 coperti, sovrapposizione, cancellazione e riapertura',()=>{const s=setup();const ids=Array.from({length:4},()=>s.create(sample).id);s.create({...sample,people:10});assert(!available(s.list(),sample.date,1,s.settings()).includes('20:45'));assert(available(s.list(),sample.date,1,s.settings()).includes('21:00'));assert.throws(()=>s.create({...sample,time:'20:00',people:1}));s.update(ids[0],{status:'cancellato'});s.create({...sample,time:'20:00'});assert.throws(()=>s.update(ids[0],{status:'confermato'}))});
test('durata variabile e tavoli multipli senza doppia assegnazione',()=>{const s=setup();s.create({...sample,people:22,tables:['T21','T22','T1'],duration:180});assert.throws(()=>s.create({...sample,people:4,tables:['T1'],time:'21:00'}));assert.throws(()=>s.create({...sample,people:22,tables:['T23']}));assert.equal(s.create({...sample,people:4,tables:['T1'],time:'22:00'}).people,4)});
test('chiusura online per giorno e servizio, manuale consentita',()=>{const s=setup();s.setClosed(sample.date,'cena',true);assert.equal(available(s.list(),sample.date,2,s.settings()).filter(t=>t>'17:00').length,0);assert.throws(()=>s.create(sample));assert(s.create({...sample,source:'phone'}));assert(s.create({...sample,time:'12:15'}));s.setClosed(sample.date,'cena',false);assert(s.create(sample))});
test('arrivo parziale, uscita, eventi e validazione',()=>{const s=setup();const b=s.create({...sample,people:4});assert.throws(()=>s.update(b.id,{status:'arrivo parziale',arrivedCount:4}));s.update(b.id,{status:'arrivo parziale',arrivedCount:2});assert.equal(s.list()[0].arrivedCount,2);s.update(b.id,{status:'arrivato'});assert.equal(s.list()[0].arrivedCount,4);s.update(b.id,{status:'uscito'});assert(s.events().length>=4);s.markRead();assert(s.events().every(e=>e.read));assert.throws(()=>s.create({...sample,people:31}));assert.throws(()=>s.create({...sample,date:'2099-02-30'}))});
test('scenario da 130 su giornata vuota e conservazione dati v1',()=>{const s=setup();s.loadScenario(sample.date);assert.equal(s.list().reduce((n,b)=>n+b.people,0),130);assert.throws(()=>s.loadScenario(sample.date));assert.throws(()=>s.setSettings({capacity:129}));s.save([{...sample,id:'legacy'}]);assert.deepEqual(s.list()[0].tables,[]);assert.equal(s.list()[0].duration,120)});
test('calendario settimanale: chiusure, orari personalizzati e conservazione delle prenotazioni',()=>{const s=setup(),b=s.create(sample),weekly=s.settings().weekly,day=new Date(sample.date+'T12:00:00Z').getUTCDay();weekly[day].open=false;s.setSettings({weekly});assert.deepEqual(available(s.list(),sample.date,2,s.settings()),[]);assert.throws(()=>s.create(sample));assert.equal(s.list().find(x=>x.id===b.id).status,'prenotato');s.update(b.id,{status:'confermato'});assert(s.create({...sample,source:'phone',time:'18:00'}));weekly[day].open=true;weekly[day].pranzo.enabled=false;weekly[day].cena={enabled:true,start:'18:15',end:'18:45'};s.setSettings({weekly});assert.deepEqual(available(s.list(),sample.date,2,s.settings()),['18:15','18:30','18:45']);assert(s.create({...sample,time:'18:15',people:2}));assert.throws(()=>s.create({...sample,time:'19:00'}));s.setClosed(sample.date,'cena',true);assert.deepEqual(available(s.list(),sample.date,2,s.settings()),[]);assert.deepEqual(new BookingStore(s.storage).settings().weekly,weekly)});
test('calendario: intervalli non validi rifiutati senza sovrascrivere impostazioni',()=>{const s=setup();for(const hours of [{enabled:true,start:'20:00',end:'19:00'},{enabled:true,start:'18:07',end:'20:00'},{enabled:true,start:'16:00',end:'19:00'}]){const weekly=s.settings().weekly;weekly[1].cena=hours;assert.throws(()=>s.setSettings({weekly}));assert.equal(s.settings().weekly[1].cena.start,'19:00')}const weekly=s.settings().weekly;weekly[1].pranzo.enabled=false;weekly[1].cena.enabled=false;assert.throws(()=>s.setSettings({weekly}));});
test('sale configurabili: capienza, assegnazioni, rinomina e persistenza',()=>{const s=setup();s.setLayout({rooms:['Sala test'],tables:[{id:'A',name:'Tavolo A',room:'Sala test',seats:8},{id:'B',name:'Tavolo B',room:'Sala test',seats:4}]});assert.equal(s.settings().capacity,12);const b=s.create({...sample,people:8,tables:['A']});assert.throws(()=>s.create({...sample,people:8}));assert.throws(()=>s.setLayout({rooms:['Sala test'],tables:[{id:'B',name:'B',room:'Sala test',seats:12}]}));let layout=s.layout();layout.tables[0].seats=6;assert.throws(()=>s.setLayout(layout));assert.equal(s.layout().tables[0].seats,8);layout=s.layout();layout.rooms=['Terrazza'];layout.tables.forEach(t=>t.room='Terrazza');layout.tables[0].name='Grande';s.setLayout(layout);assert.equal(s.list()[0].tables[0],'A');assert.equal(new BookingStore(s.storage).layout().tables[0].name,'Grande');assert.throws(()=>s.setSettings({capacity:13}));s.update(b.id,{tables:[]});s.setLayout({rooms:['Terrazza'],tables:[{id:'B',name:'B',room:'Terrazza',seats:12}]});assert.equal(s.layout().tables.length,1);});
test('sale configurabili: nomi duplicati e posti errati rifiutati',()=>{const s=setup();for(const seats of [0,31,2.5])assert.throws(()=>s.setLayout({rooms:['A'],tables:[{id:'a',name:'A',room:'A',seats}]}));const layout=s.layout();layout.rooms.push('sala principale');assert.throws(()=>s.setLayout(layout));assert.equal(s.settings().capacity,130)});
